---
services:
  jwt-init-fullnode:
    container_name: jwt-init-fullnode
    image: alpine:3.22.0
    volumes:
      - jwttoken-fullnode:/jwt
    healthcheck:
      test: [CMD, test, -f, /jwt/jwt.hex]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  ev-reth-fullnode:
    container_name: ev-reth-fullnode
    image: ghcr.io/evstack/ev-reth:latest
    depends_on:
      jwt-init-fullnode:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - $FULLNODE_EV_RETH_RPC_PORT:8545
      - $FULLNODE_EV_RETH_PROMETHEUS_PORT:9001
    restart: always
    volumes:
      - ../single-sequencer/genesis.json:/root/genesis.json:ro
      - ./entrypoint.ev-reth.sh:/entrypoint.sh
      - jwttoken-fullnode:/root/jwt:ro
      - ev-reth-fullnode-data:/root/reth
      - ../../lib/logging.sh:/usr/local/lib/logging.sh:ro
    entrypoint: /entrypoint.sh
    command:
      - node
      - --ev-reth.enable
      - --engine.persistence-threshold=0
      - --engine.memory-block-buffer-target=0
      - --engine.always-process-payload-attributes-on-canonical-head
      - --chain=/root/genesis.json
      - --metrics=0.0.0.0:9001
      - --log.file.directory=/root/logs
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/root/jwt/jwt.hex
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=all
      - --disable-discovery
      - --txpool.pending-max-count=200000
      - --txpool.pending-max-size=200
      - --txpool.queued-max-count=200000
      - --txpool.queued-max-size=200
      - --txpool.max-account-slots=2048
      - --txpool.max-new-txns=2048
      - --txpool.additional-validation-tasks=16
      - --datadir=/root/reth
    networks:
      - evstack_shared

  fullnode:
    container_name: fullnode
    image: ghcr.io/evstack/ev-node-evm-single:main
    ports:
      - $FULLNODE_EV_NODE_RPC_PORT:7331
      - $FULLNODE_EV_NODE_PROMETHEUS_PORT:26660
    restart: always
    depends_on:
      ev-reth-fullnode:
        condition: service_started
    volumes:
      - fullnode-data:/root/.evm-single
      - jwttoken-fullnode:/root/jwt:ro
      - sequencer-export:/volumes/sequencer_export
      - ./entrypoint.fullnode.sh:/usr/bin/entrypoint.sh
      - ../../lib/logging.sh:/usr/local/lib/logging.sh:ro
    command:
      - start
      - --evnode.rpc.address=0.0.0.0:7331
      - --evnode.p2p.listen_address=/ip4/0.0.0.0/tcp/7676
      - --evnode.instrumentation.prometheus
      - --evnode.instrumentation.prometheus_listen_addr=:26660
    environment:
      - EVM_ENGINE_URL=http://ev-reth-fullnode:8551
      - EVM_ETH_URL=http://ev-reth-fullnode:8545
      - EVM_JWT_PATH=/root/jwt/jwt.hex
      - EVM_BLOCK_TIME=500ms
      - DA_BLOCK_TIME=30s
      - DA_ADDRESS=http://local-da:7980
    networks:
      - evstack_shared

volumes:
  jwttoken-fullnode:
    driver: local
  ev-reth-fullnode-data:
    driver: local
  fullnode-data:
    driver: local
  sequencer-export:
    external: true
    name: sequencer-export

networks:
  evstack_shared:
    external: true
